import type { Issue, IssueCategory, IssuePriority, IssueStatus } from "./types";

export const CATEGORIES: IssueCategory[] = [
  "Electrical",
  "Plumbing & Water",
  "Wi-Fi & Network",
  "Cleanliness & Hygiene",
  "Furniture & Fixtures",
  "Classroom & AV",
  "Laboratory Equipment",
  "Washroom Facilities",
  "Library & Study Hall",
  "Other",
];

export const STATUSES: { value: IssueStatus | "all"; label: string }[] = [
  { value: "all", label: "All Statuses" },
  { value: "new", label: "New Report" },
  { value: "assigned", label: "Assigned" },
  { value: "in_progress", label: "In Progress" },
  { value: "escalated", label: "Escalated" },
  { value: "awaiting_confirmation", label: "Awaiting Confirmation" },
  { value: "resolved", label: "Resolved" },
  { value: "closed", label: "Closed & Verified" },
];

export const PRIORITIES: { value: IssuePriority | "all"; label: string }[] = [
  { value: "all", label: "All Priorities" },
  { value: "critical", label: "Critical" },
  { value: "high", label: "High Priority" },
  { value: "medium", label: "Medium" },
  { value: "low", label: "Low" },
];

export const STATUS_LABELS: Record<IssueStatus, string> = {
  new: "New Report",
  assigned: "Assigned",
  in_progress: "In Progress",
  escalated: "Escalated",
  awaiting_confirmation: "Awaiting Confirmation",
  resolved: "Resolved",
  closed: "Closed & Verified",
};

/** Pastel sticky-note colors matching the reference board */
export const CATEGORY_COLORS: Record<IssueCategory, string> = {
  "Wi-Fi & Network": "#EDE4FF",
  "Plumbing & Water": "#D9F0FF",
  Electrical: "#FFF3C4",
  "Washroom Facilities": "#FFE0EC",
  "Classroom & AV": "#E0F7E9",
  "Library & Study Hall": "#FFE8D6",
  "Cleanliness & Hygiene": "#E5F6E8",
  "Laboratory Equipment": "#E8EEFF",
  "Furniture & Fixtures": "#FFF0D6",
  Other: "#F3F4F6",
};

export const SAMPLE_PHOTO =
  "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80";

export const DEMO_ISSUES: Omit<Issue, "$id" | "$createdAt" | "$updatedAt">[] = [
  {
    ticketId: "CF-1001",
    title: "Wi-Fi completely down in Block B 3rd Floor",
    description:
      "No connectivity across labs and hallway since morning. Students unable to access LMS or submit assignments.",
    category: "Wi-Fi & Network",
    building: "Block B - Academic Wing",
    room: "3rd Floor Hallway & Lab 301",
    priority: "high",
    status: "escalated",
    photoUrl: SAMPLE_PHOTO,
    reporterId: "demo-aarav",
    reporterName: "Aarav Sharma",
    assigneeId: "",
    assigneeName: "",
    upvoteCount: 221,
    commentCount: 4,
  },
  {
    ticketId: "CF-1002",
    title: "Major Water Leakage Near Main Canteen Entrance",
    description:
      "Overhead pipeline leaking dirty water onto the walkway. Slippery floor and water pooling near food counters.",
    category: "Plumbing & Water",
    building: "Main Canteen Complex",
    room: "Entrance Corridor",
    priority: "high",
    status: "escalated",
    photoUrl: SAMPLE_PHOTO,
    reporterId: "demo-aarav",
    reporterName: "Aarav Sharma",
    assigneeId: "",
    assigneeName: "",
    upvoteCount: 198,
    commentCount: 6,
  },
  {
    ticketId: "CF-1006",
    title: "Broken Flush & Broken Door Lock in Girls Washroom 1st Floor",
    description:
      "Two stalls unusable. Door lock jammed and flush mechanism broken. Urgent for morning lecture rush.",
    category: "Washroom Facilities",
    building: "Block A - Girls Wing",
    room: "1st Floor Washroom",
    priority: "high",
    status: "escalated",
    photoUrl: SAMPLE_PHOTO,
    reporterId: "demo-meera",
    reporterName: "Meera Patel",
    assigneeId: "",
    assigneeName: "",
    upvoteCount: 176,
    commentCount: 3,
  },
  {
    ticketId: "CF-1003",
    title: "Sparks from corridor switchboard near Lab 204",
    description:
      "Switchboard making crackling sounds and occasional sparks when lights are toggled.",
    category: "Electrical",
    building: "Block C - Labs",
    room: "Outside Lab 204",
    priority: "critical",
    status: "in_progress",
    photoUrl: SAMPLE_PHOTO,
    reporterId: "demo-rahul",
    reporterName: "Rahul Verma",
    assigneeId: "demo-worker",
    assigneeName: "Facilities Staff",
    upvoteCount: 142,
    commentCount: 5,
  },
  {
    ticketId: "CF-1004",
    title: "Broken projector in Seminar Hall 2",
    description:
      "Projector shows blank screen. HDMI input not detected. Classes disrupted.",
    category: "Classroom & AV",
    building: "Seminar Complex",
    room: "Seminar Hall 2",
    priority: "medium",
    status: "assigned",
    photoUrl: "",
    reporterId: "demo-aarav",
    reporterName: "Aarav Sharma",
    assigneeId: "demo-worker",
    assigneeName: "Facilities Staff",
    upvoteCount: 88,
    commentCount: 2,
  },
  {
    ticketId: "CF-1005",
    title: "Library AC not cooling reading hall",
    description:
      "Temperature stays high all afternoon. Students leaving early due to heat.",
    category: "Library & Study Hall",
    building: "Central Library",
    room: "Reading Hall A",
    priority: "medium",
    status: "new",
    photoUrl: "",
    reporterId: "demo-meera",
    reporterName: "Meera Patel",
    assigneeId: "",
    assigneeName: "",
    upvoteCount: 64,
    commentCount: 1,
  },
  {
    ticketId: "CF-1007",
    title: "Overflowing bins near Hostel Block D",
    description:
      "Garbage not collected for 3 days. Strong smell and flies around entrance.",
    category: "Cleanliness & Hygiene",
    building: "Hostel Block D",
    room: "Main Entrance",
    priority: "medium",
    status: "new",
    photoUrl: SAMPLE_PHOTO,
    reporterId: "demo-rahul",
    reporterName: "Rahul Verma",
    assigneeId: "",
    assigneeName: "",
    upvoteCount: 51,
    commentCount: 2,
  },
  {
    ticketId: "CF-1008",
    title: "Broken bench in open courtyard",
    description:
      "Wooden bench collapsed on one side. Sharp edges exposed — safety risk.",
    category: "Furniture & Fixtures",
    building: "Open Courtyard",
    room: "Near Fountain",
    priority: "low",
    status: "resolved",
    photoUrl: "",
    reporterId: "demo-aarav",
    reporterName: "Aarav Sharma",
    assigneeId: "demo-worker",
    assigneeName: "Facilities Staff",
    upvoteCount: 29,
    commentCount: 1,
  },
  {
    ticketId: "CF-1009",
    title: "Chemistry lab fume hood fan offline",
    description:
      "Exhaust fan not spinning. Practicals postponed for safety compliance.",
    category: "Laboratory Equipment",
    building: "Science Block",
    room: "Chem Lab 1",
    priority: "high",
    status: "assigned",
    photoUrl: SAMPLE_PHOTO,
    reporterId: "demo-meera",
    reporterName: "Meera Patel",
    assigneeId: "demo-worker",
    assigneeName: "Facilities Staff",
    upvoteCount: 97,
    commentCount: 3,
  },
  {
    ticketId: "CF-1010",
    title: "Flickering lights in parking basement",
    description:
      "Half the lights flicker after sunset. Visibility is poor for two-wheelers.",
    category: "Electrical",
    building: "Parking Basement",
    room: "Zone B",
    priority: "medium",
    status: "in_progress",
    photoUrl: "",
    reporterId: "demo-rahul",
    reporterName: "Rahul Verma",
    assigneeId: "demo-worker",
    assigneeName: "Facilities Staff",
    upvoteCount: 43,
    commentCount: 0,
  },
  {
    ticketId: "CF-1011",
    title: "Leaking tap in boys washroom Block C",
    description: "Continuous drip wasting water. Floor stays wet near sinks.",
    category: "Plumbing & Water",
    building: "Block C",
    room: "Ground Floor Washroom",
    priority: "low",
    status: "new",
    photoUrl: "",
    reporterId: "demo-aarav",
    reporterName: "Aarav Sharma",
    assigneeId: "",
    assigneeName: "",
    upvoteCount: 18,
    commentCount: 0,
  },
  {
    ticketId: "CF-1012",
    title: "Router offline in hostel wing 2",
    description: "Entire wing disconnected since yesterday evening.",
    category: "Wi-Fi & Network",
    building: "Hostel Block B",
    room: "Wing 2",
    priority: "high",
    status: "new",
    photoUrl: "",
    reporterId: "demo-meera",
    reporterName: "Meera Patel",
    assigneeId: "",
    assigneeName: "",
    upvoteCount: 112,
    commentCount: 4,
  },
  {
    ticketId: "CF-1013",
    title: "Broken classroom chair row in LH-12",
    description: "Three seats missing bolts. Students sitting on floor.",
    category: "Furniture & Fixtures",
    building: "Lecture Hall Complex",
    room: "LH-12",
    priority: "low",
    status: "closed",
    photoUrl: "",
    reporterId: "demo-rahul",
    reporterName: "Rahul Verma",
    assigneeId: "demo-worker",
    assigneeName: "Facilities Staff",
    upvoteCount: 22,
    commentCount: 1,
  },
  {
    ticketId: "CF-1014",
    title: "Muddy puddles after rain near Gate 2",
    description: "Drainage clogged. Students tracking mud into academic blocks.",
    category: "Cleanliness & Hygiene",
    building: "Campus Gate 2",
    room: "Approach Road",
    priority: "medium",
    status: "resolved",
    photoUrl: SAMPLE_PHOTO,
    reporterId: "demo-aarav",
    reporterName: "Aarav Sharma",
    assigneeId: "demo-worker",
    assigneeName: "Facilities Staff",
    upvoteCount: 35,
    commentCount: 2,
  },
  {
    ticketId: "CF-1015",
    title: "Mic not working in AV Classroom 3",
    description: "Wireless mic dead. Backup wired mic also crackling.",
    category: "Classroom & AV",
    building: "AV Block",
    room: "Classroom 3",
    priority: "medium",
    status: "assigned",
    photoUrl: "",
    reporterId: "demo-meera",
    reporterName: "Meera Patel",
    assigneeId: "demo-worker",
    assigneeName: "Facilities Staff",
    upvoteCount: 57,
    commentCount: 1,
  },
];

export function isAppwriteConfigured() {
  const project = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID;
  return Boolean(project && project !== "your_project_id");
}
